spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-323b5f05-ansh62949-c765.j.aivencloud.com:17366}
    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
      sasl.mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
      sasl.jaas.config: ${KAFKA_JAAS_CONFIG}
      ssl.engine.factory.class: com.herride.backend.config.TrustAllSslEngineFactory

jwt:
  secret: ${JWT_SECRET}

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
  kafka:
    replication-factor: ${KAFKA_REPLICATION_FACTOR:2}
  jwt:
    secret: ${JWT_SECRET}
